# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/Projects/IbisOS/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/Projects/IbisOS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/Projects/IbisOS/CMakeFiles /media/Projects/IbisOS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/Projects/IbisOS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IbisOS.bin

# Build rule for target.
IbisOS.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IbisOS.bin
.PHONY : IbisOS.bin

# fast build rule for target.
IbisOS.bin/fast:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/build
.PHONY : IbisOS.bin/fast

boot/boot.o: boot/boot.asm.o

.PHONY : boot/boot.o

# target to build an object file
boot/boot.asm.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/boot/boot.asm.o
.PHONY : boot/boot.asm.o

boot/gdt.o: boot/gdt.asm.o

.PHONY : boot/gdt.o

# target to build an object file
boot/gdt.asm.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/boot/gdt.asm.o
.PHONY : boot/gdt.asm.o

boot/idt.o: boot/idt.asm.o

.PHONY : boot/idt.o

# target to build an object file
boot/idt.asm.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/boot/idt.asm.o
.PHONY : boot/idt.asm.o

boot/interrupt.o: boot/interrupt.asm.o

.PHONY : boot/interrupt.o

# target to build an object file
boot/interrupt.asm.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/boot/interrupt.asm.o
.PHONY : boot/interrupt.asm.o

memcpy/memcpy.o: memcpy/memcpy.cpp.o

.PHONY : memcpy/memcpy.o

# target to build an object file
memcpy/memcpy.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memcpy/memcpy.cpp.o
.PHONY : memcpy/memcpy.cpp.o

memcpy/memcpy.i: memcpy/memcpy.cpp.i

.PHONY : memcpy/memcpy.i

# target to preprocess a source file
memcpy/memcpy.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memcpy/memcpy.cpp.i
.PHONY : memcpy/memcpy.cpp.i

memcpy/memcpy.s: memcpy/memcpy.cpp.s

.PHONY : memcpy/memcpy.s

# target to generate assembly for a file
memcpy/memcpy.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memcpy/memcpy.cpp.s
.PHONY : memcpy/memcpy.cpp.s

memset/memset.o: memset/memset.cpp.o

.PHONY : memset/memset.o

# target to build an object file
memset/memset.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memset/memset.cpp.o
.PHONY : memset/memset.cpp.o

memset/memset.i: memset/memset.cpp.i

.PHONY : memset/memset.i

# target to preprocess a source file
memset/memset.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memset/memset.cpp.i
.PHONY : memset/memset.cpp.i

memset/memset.s: memset/memset.cpp.s

.PHONY : memset/memset.s

# target to generate assembly for a file
memset/memset.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/memset/memset.cpp.s
.PHONY : memset/memset.cpp.s

minikernel/minikernel.o: minikernel/minikernel.cpp.o

.PHONY : minikernel/minikernel.o

# target to build an object file
minikernel/minikernel.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/minikernel/minikernel.cpp.o
.PHONY : minikernel/minikernel.cpp.o

minikernel/minikernel.i: minikernel/minikernel.cpp.i

.PHONY : minikernel/minikernel.i

# target to preprocess a source file
minikernel/minikernel.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/minikernel/minikernel.cpp.i
.PHONY : minikernel/minikernel.cpp.i

minikernel/minikernel.s: minikernel/minikernel.cpp.s

.PHONY : minikernel/minikernel.s

# target to generate assembly for a file
minikernel/minikernel.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/minikernel/minikernel.cpp.s
.PHONY : minikernel/minikernel.cpp.s

tables/gdt.o: tables/gdt.cpp.o

.PHONY : tables/gdt.o

# target to build an object file
tables/gdt.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/gdt.cpp.o
.PHONY : tables/gdt.cpp.o

tables/gdt.i: tables/gdt.cpp.i

.PHONY : tables/gdt.i

# target to preprocess a source file
tables/gdt.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/gdt.cpp.i
.PHONY : tables/gdt.cpp.i

tables/gdt.s: tables/gdt.cpp.s

.PHONY : tables/gdt.s

# target to generate assembly for a file
tables/gdt.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/gdt.cpp.s
.PHONY : tables/gdt.cpp.s

tables/idt.o: tables/idt.cpp.o

.PHONY : tables/idt.o

# target to build an object file
tables/idt.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/idt.cpp.o
.PHONY : tables/idt.cpp.o

tables/idt.i: tables/idt.cpp.i

.PHONY : tables/idt.i

# target to preprocess a source file
tables/idt.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/idt.cpp.i
.PHONY : tables/idt.cpp.i

tables/idt.s: tables/idt.cpp.s

.PHONY : tables/idt.s

# target to generate assembly for a file
tables/idt.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/idt.cpp.s
.PHONY : tables/idt.cpp.s

tables/isr.o: tables/isr.cpp.o

.PHONY : tables/isr.o

# target to build an object file
tables/isr.cpp.o:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/isr.cpp.o
.PHONY : tables/isr.cpp.o

tables/isr.i: tables/isr.cpp.i

.PHONY : tables/isr.i

# target to preprocess a source file
tables/isr.cpp.i:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/isr.cpp.i
.PHONY : tables/isr.cpp.i

tables/isr.s: tables/isr.cpp.s

.PHONY : tables/isr.s

# target to generate assembly for a file
tables/isr.cpp.s:
	$(MAKE) -f CMakeFiles/IbisOS.bin.dir/build.make CMakeFiles/IbisOS.bin.dir/tables/isr.cpp.s
.PHONY : tables/isr.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... IbisOS.bin"
	@echo "... boot/boot.o"
	@echo "... boot/gdt.o"
	@echo "... boot/idt.o"
	@echo "... boot/interrupt.o"
	@echo "... memcpy/memcpy.o"
	@echo "... memcpy/memcpy.i"
	@echo "... memcpy/memcpy.s"
	@echo "... memset/memset.o"
	@echo "... memset/memset.i"
	@echo "... memset/memset.s"
	@echo "... minikernel/minikernel.o"
	@echo "... minikernel/minikernel.i"
	@echo "... minikernel/minikernel.s"
	@echo "... tables/gdt.o"
	@echo "... tables/gdt.i"
	@echo "... tables/gdt.s"
	@echo "... tables/idt.o"
	@echo "... tables/idt.i"
	@echo "... tables/idt.s"
	@echo "... tables/isr.o"
	@echo "... tables/isr.i"
	@echo "... tables/isr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

